- update to check at least %{_libdir}/mozilla if there is no   MOZILLA_FIVE_HOME variable found already.
Changed files:
    monodevelop-MOZILLA_FIVE_HOME.patch -> 1.4

diff --git a/monodevelop-MOZILLA_FIVE_HOME.patch b/monodevelop-MOZILLA_FIVE_HOME.patch
--- a/monodevelop-MOZILLA_FIVE_HOME.patch
+++ b/monodevelop-MOZILLA_FIVE_HOME.patch
@@ -1,7 +1,7 @@
 diff -Nuard monodevelop-0.5.orig/monodevelop.in monodevelop-0.5/monodevelop.in
 --- monodevelop-0.5.orig/monodevelop.in	2004-06-27 06:03:48.000000000 +0200
-+++ monodevelop-0.5/monodevelop.in	2004-07-04 08:25:07.955391896 +0200
-@@ -18,8 +18,8 @@
++++ monodevelop-0.5/monodevelop.in	2004-07-04 11:58:51.216191328 +0200
+@@ -18,10 +18,12 @@
  
  if test -n "$MOZILLA_FIVE_HOME"; then
  	MOZILLA_HOME=$MOZILLA_FIVE_HOME
@@ -11,4 +11,8 @@ diff -Nuard monodevelop-0.5.orig/monodevelop.in monodevelop-0.5/monodevelop.in
 +        MOZILLA_HOME=@MOZILLA_HOME@/mozilla
  elif [ $(which mozilla) ] && grep MOZILLA_FIVE_HOME= "$(which mozilla)" > /dev/null ; then
  	MOZILLA_HOME=$(grep MOZILLA_FIVE_HOME= $(which mozilla) | cut -d '"' -f 2)
++elif [ -f @libdir@/mozilla/chrome/comm.jar ]; then
++        MOZILLA_HOME=@libdir@/mozilla
  else
+ 	echo "Cannot find mozilla installation directory. Please set MOZILLA_FIVE_HOME to your mozilla directory"
+ 	exit 1
